### ISSUE TITLE
Unable to leave event

### ISSUE THREAD

**Issue by HenryTseTse** [gcivil-nyu-org/Team_Team3_CS-GY-6063-Fall2021#215]
I was able to join an event with 0 people needed, now I am unable to leave the event. and it is stuck on my home page. There needs to be a way to not allow users to post events with 0 people needed, and/or able to leave an event when there's 0 people need
![Screen Shot 2021-11-18 at 6 48 39 PM](https://user-images.githubusercontent.com/33527580/142514885-cb1b3ff2-de93-41ee-a99e-a2f93d932eea.png)
![Screen Shot 2021-11-18 at 6 49 49 PM](https://user-images.githubusercontent.com/33527580/142514887-99ec8257-6fb6-4cbc-91f5-d88f56240683.png)
ed

**Comment by barksdaleaz** [comment]
I was also unable to find an "unjoin" button.
