### ISSUE TITLE
As a user, I want to log into my account using my correct username and password so that I can interact with the application. 

### ISSUE THREAD

**Issue by jk1257** [gcivil-nyu-org/Team_Team3_CS-GY-6063-Fall2021#22]
Acceptance Criteria:
- The home page shows a link for the user to log in 
- This redirects them to a page where they can enter their username and password
- If correct, they can press a button and it takes them to their profile page
- If incorrect, user is prompted that their username and password do not match

Definition of Done:
- Design completed
- Code completed
- Code reviewed
- Acceptance tested
- Live on production server

**Comment by marcuspoon2** [comment]
TASKS
- Build out login form to collect email address and password 
- Verify email and password combination exists in the database so user can log in
