### ISSUE TITLE
The website broke by joining events again

### ISSUE THREAD

**Issue by Pragdheeshnyu** [gcivil-nyu-org/Team_Team3_CS-GY-6063-Fall2021#226]
When we click on Join event, the website redirects to a page that says I have joined the event. Now, when clicked on the back button, the webpage shows the 'Join Event' button again. When clicking on that button again, the query broke the website throwing an error. The screenshot is attached.
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/71206520/142560797-daa2af77-e1bc-4b4e-b578-afda56edaac7.png">

**Comment by marcuspoon2** [comment]
we couldn't replicate, we think we fixed through other PR's. closing
