### ISSUE TITLE
[Bug] Invalid date for a valid date

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/Team_Team3_CS-GY-6063-Fall2021#241]
When adding an event, it shows my date is invalid.

1. Type in a "invalid" date (year 23421)
2. Re-type a "valid" date (year 2022)

![image](https://user-images.githubusercontent.com/60978943/142700430-0bcbded9-ae7e-45a7-a1b0-41b965011a63.png)

**Comment by marcuspoon2** [comment]
2/31 is an invalid date (only 28/29 days in Feb)
